environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"

platform:
- x86
- x64

# configuration: Release

os :
# - Visual Studio 2013
# - Visual Studio 2015
- Visual Studio 2017

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install -g node-gyp
- npm install -g node-pre-gyp	# to allow use as command in a console (for the build).
- npm install node-pre-gyp		# to allow use as module in a JS file (for the test).	

before_build:
- node-pre-gyp configure

build_script:
- node-pre-gyp /m build

after_build:
- node -e "process.stdout.write( process.versions.modules );process.stdout.write(require('./package.json').version)"
- if "%platform%"=="x86" set platform="ia32"
- echo | set /p="esketch-" >name || true
- node -e "process.stdout.write(require('./package.json').version);" > inter
- set /p inter= < inter
- echo | set /p=%inter% >>name || true
- echo | set /p="-node-v" >> name || true
- node -e "process.stdout.write(process.versions.modules);" > inter
- set /p inter= < inter
- echo | set /p=%inter% >>name || true
- echo | set /p="-win32-" >> name || true
- echo | set /p=%platform% >> name || true
- type name
- set /p name= <name
- echo %name%

test_script:
- node demo.js

# matrix:
  # allow_failures:
  # - os: Visual Studio 2017

